### ISSUE TITLE
[Low] Feature: tags for resources?

### ISSUE THREAD

**Issue by ChaikaBogdan** [onipot/K-Stash#3]
Now its possible to add only tags for topics, how about resources itself?
Several topics might contain same technology across saved resources.
For example ( i made it up, and its bad):
Topic **Python** (tags - python, automation)
Resource: "Python dockerization" (python, docker tags) 

Topic: **Docker** (tags - docker, automation)
Resources: "shm-size for Selenium with Chrome issue fix"(docker, selenium, chrome tags)

So by searching **docker** you will find both.

**Comment by masc-it** [comment]
@ChaikaBogdan In the initial design resources had tags too, but with the concept of "Topic" (A set of homogeneous resources) they became useless. Use Ttopics as they are meant to be used, just do not give general names (as we always do with bookmarks in order to search stuff more easily). K-Stash aim's to make your stuff more organized, not less :)

**Comment by ChaikaBogdan** [comment]
@onipot oof, guess i need to throw away trello mindset first ;)
